# ==============================================================================
# Lotus Lake Namespace Kustomization
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tf-runner-rbac.yaml
  - lotus-lake-source.yaml
  - lotus-lake-secrets.yaml
  - lotus-lake-terraform.yaml
