# ==============================================================================
# Homenetes Namespace Kustomization
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - source.yaml
  - homenetes.yaml
  # - secrets.yaml  # TODO: Add when apps need secrets
