# ==============================================================================
# Grafana OAuth Secret
# ==============================================================================
# Credentials for Authentik OAuth2 integration
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:/6AGzBTHJT85EEVoHZsThXqcgf3gtC0I1Fu4IlN8WDR3efg/YsLwiQ==,iv:6toG3Ofwx6SVs18MYvNh8lCGE8WnpX0IwJ/EuRfxHlI=,tag:Q5YIr/kEjltJhHTlk9F4xQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Y6nSbppu0KWaBzjQV1oQhwZC7B8TRHHCbM6CodTMR4Xd7zSlGOhsJ8XgPSalMv07bha3GytKooQ5fqKUE+HU0ygryup1++ulWpdwrdWX9KIAE8n0ZthTI+O8ig2C3JMD8ZBKYNhX5mvYYy/xQG6ERRWKyOSDNBfs5VeiDbV0Fvw=,iv:oNvofWboZvHUrrh6DFoVzhzxY24AUVPxbeIIU0HPYhw=,tag:fwQt2LidSbG6CsYFz3nYvg==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WERLbEdLV2Q1VTZuR0xJ
            c0hSTnJ3eVVwVjY3SWxRR010VXJJdUFVOEZVCjNvRllSWUllTnJ3WjZZTUpROVVZ
            Yi9uWWZNRTR3ZC9YYkxLaHJFNm9vSFUKLS0tIFp4bHdlb0dQMDV4ZFR2amJKNlE0
            TWdKSVFCdUYzNGg0TWxma2tqa2d1ckkKZqXOZD931AGHnm9cug+Eu4WM7Ny5dyGG
            WPxge70DiEsKSx84ExiJUxW9HT+zhi5K1XR4hZbP4lcF3R3WzFMlKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T23:11:53Z"
    mac: ENC[AES256_GCM,data:iLYQWTFCIMRfP+IfK/3UesDzShfbkDxAk3ZMNaBWbDxrp1lic+RPQSweeywfH1kNnJqXmZz2mdph94SWkmyj/qdYhEophzPvlcbAC/S1hob3/WJiHER6t6Jpj9AAPxcNnQCsJja85npgscl/0qPDaw8IDloNXXH97ooy9Ldvtd8=,iv:KG8WFnrB+AnPVDOPhhq+Top4RvLRHnw4xk6hUSPe0Ck=,tag:EQbwZi8p/N+uTzRpYUiq5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
