# ==============================================================================
# Grafana OAuth Secret
# ==============================================================================
# Credentials for Authentik OAuth2 integration
# TODO: Encrypt with SOPS
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:V7+geFMJ3jBE8Fy9vbo22TpZdUjYXRuWm124BZj3IzsxrltPCUHXPQ==,iv:sd1rs6sjL4MR0zDxK7i2ni3xrHXHkWOHZaiG6Nw4KYk=,tag:aEtP6lwaCbmmZkmClNyUyg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:tMLj3JaZ2OJcBk2+K5EUoPi6Q5WSLQRlO8wqC+ZRuvooWIfNgmjbTQp2iDy0bEiDynKOO/nC4jymF11SpTaInqeT3u1Foga2Xmf6FdXD6gqfOlYvi6dYcATjsHbnw6l6lrzsznK8jIhth0lXCB8gyBzN05zdZ+Zbw6Spln/yMwY=,iv:/oZ9IQ8L7TrsGC8qIjI2mirV3sNOPzzcmlHIi0RY08Y=,tag:LvFJ8Lo7ZKG0UBpGrRWfiA==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVk9VWlZwVERlQ1hHY00z
            YzI0K0pQK0h6MWtNR1l0OE8zQUViVW9NUlNVCnBINFh2UUNTVm9vcjdmNnZnK0Qv
            NkNqdUtiV2g3aG5mbFNZY0tjVGNuTm8KLS0tIE9VbDd4cE1pWFhJam0vbWJEQU9P
            R3FjRWpDMWlOcjArSENrRi9HS2sydnMKwcrKQT9/SUW3ZYcAf8fxcJ57NYbq60bi
            /Gs2Xg1Z3+ELtgX/N6PJ5wp923DeAOg39qkfHMhxcsvBv0yOsEVaBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T22:06:29Z"
    mac: ENC[AES256_GCM,data:Ya5ZsZQrvxDS7bx55FR2ImszAf/i/p0hf2ijqyBt7PySV1T0SqTg9hYM/AnEWKvLT64/M4SzaMH//ygWfZNHvfFfqZbaTYIN2GJBHeLDG79+aTEwf8k5RVdSYgPfIiXcs+/b6NPbTATSdAdW5dHmHkv6qDm/DdBNxk/RQKG6rEo=,iv:Lfw/uIqAQI55JAVe2GMAYAxqwWn7HD3IAzvku80OPpQ=,tag:1dQO/JprKipEbyNvxe++pQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
