# ==============================================================================
# SeaweedFS
# ==============================================================================
# TODO: Distributed storage with S3 API
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []