# ==============================================================================
# Root Kustomization
# ==============================================================================
# Entry point for Flux - references all subdirectories
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- infrastructure
  #- apps