# ==============================================================================
# Headscale UI Service
# ==============================================================================

apiVersion: v1
kind: Service
metadata:
  name: headscale-ui
  namespace: headscale-ui
spec:
  selector:
    app: headscale-ui
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
