# ==============================================================================
# SeaweedFS Kustomization
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - s3-auth-secret.yaml
  - release.yaml
  - csi-repository.yaml
  - csi-release.yaml
