# ==============================================================================
# Vault Kustomization
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - backup-secret.yaml
  - database.yaml
  - release.yaml
  - ingress.yaml
