# ==============================================================================
# Authentik Kustomization
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - database.yaml
  - secrets.yaml
  - backup-secret.yaml
  - release.yaml
