# ==============================================================================
# Airbyte Database Config Secret
# ==============================================================================
# TODO: Use external-secrets to sync from CNPG secret
apiVersion: v1
kind: Secret
metadata:
    name: airbyte-db-config
    namespace: airbyte
type: Opaque
stringData:
    DATABASE_USER: ENC[AES256_GCM,data:Kjb2tzoiZQ==,iv:urKovv/3i7Sj6+pMrVPptu5Z8rbPxOCYBQv79t6ooRo=,tag:YEFdkI/mxv5sWl050CGRPw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:HAwF6HyMXevyGQXIaYjQeWSpodLiFPTF8/Zk7WHgrRYX2FCOfolF91vg17oPgcE9V4f3fD6+chCCiHzAItTIig==,iv:Ic6xkTvUv1gP6Vb7jwBT2P8xuesnKAmWsLMkcB0Mdkc=,tag:2dA2Mfrm1EJKD866gJCT7w==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNTRNZ3RPZ0NmMUl6L29w
            ZmwyWVpVR3VLWWpEa25BZERjMDFvaGE3d3lZCjlra215TlAyL0I0U09UZDMzVFox
            QlhocUEyeFdPM3cvYmFZRnVzaks3RmcKLS0tIDhjMmZWQ2V0QmgxU0UyWS9Kd0Nz
            R1JSem13ZkRHSUx4SkhROHRvMGVzUjQKxvRmFFi0kjD1GoPHD90/Y7B5EWBrOPlL
            wpOgvtPfY4VVKpFOKr5tkHhFYk7CxgtHjZ6EfVYpznBDPK3DgEp86w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T08:10:43Z"
    mac: ENC[AES256_GCM,data:1EtCZoEimPuEu/vHkF6HJvLHKaJbmxlP4IMF/O6uL59+9KQMH0GxyANX+GKpMUotpuLGQTgtIL6vS77L8D70Anbu+5qe92v7nQD+3/IODh+ew1xdzTnPL1/MfAW5xESGD+m2SKhV38T9yDGIm2mJwLShMZhl8vKpqHk+OgxT6PQ=,iv:GqC9iX0jB0gtQERNq/PYeagj0L5C0f6vl9aGMZYIbys=,tag:JiFigo3rpxlYVsQjY1r+0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
